stages:
- build
- test 

build:
  stage: build
  script:
    - cd GroupProjectApi   
    - ./gradlew build -x test
    - ./gradlew.bat --stop 
test:
  stage: test
  script:
    - cd GroupProjectApi   
    - ./gradlew test
    - ./gradlew.bat --stop
