
stages:
- build
- test 
- sonarqube

build:
  stage: build
  script:
    - cd GroupProjectApi   
    - ./gradlew build -x test
    - ./gradlew.bat --stop 
test:
  stage: test
  script:
    - cd S3_IP_Muziekzaals
    - ./gradlew test
    - ./gradlew sonarqube
    - ./gradlew.bat --stop

sonarqube:
  stage: sonarqube
  script:
    - git fetch --unshallow
    - cd S3_IP_Muziekzaals  
    - ./gradlew sonarqube
    - ./gradlew.bat --stop


